In [1]:
import torch
from yolox.models import YOLOXHeadAttr, YOLOXHead, YOLOPAFPN, YOLOX
from yolox.data.datasets import DTLD_ATTRIBUTES

from yolox.utils import get_model_info

In [3]:
dummy_input = torch.rand((1,3,640,640))

In [6]:
backbone = YOLOPAFPN(1, 1, in_channels=[256, 512, 1024])
head = YOLOXHead(1, 1, in_channels=[256, 512, 1024])
model = YOLOX(backbone, head)

print(get_model_info(model, (640, 640)))

model.eval()
res = model(dummy_input)
print(res)
print(res.shape)

Params: 54.15M, Gflops: 155.31
tensor([[[-1.0282e-01,  2.0892e-01,  8.4914e+00,  7.9307e+00,  5.1047e-01,
           5.0491e-01],
         [ 7.8972e+00,  2.0892e-01,  8.4914e+00,  7.9307e+00,  5.1047e-01,
           5.0491e-01],
         [ 1.5897e+01,  2.0892e-01,  8.4914e+00,  7.9307e+00,  5.1047e-01,
           5.0491e-01],
         ...,
         [ 5.4369e+02,  6.0954e+02,  3.0700e+01,  3.1774e+01,  5.1122e-01,
           5.1305e-01],
         [ 5.7569e+02,  6.0954e+02,  3.0700e+01,  3.1774e+01,  5.1122e-01,
           5.1305e-01],
         [ 6.0769e+02,  6.0954e+02,  3.0700e+01,  3.1774e+01,  5.1122e-01,
           5.1305e-01]]], grad_fn=<AsStridedBackward>)
torch.Size([1, 8400, 6])


In [7]:
backbone2 = YOLOPAFPN(1, 1, in_channels=[256, 512, 1024])
head2 = YOLOXHeadAttr(1, 1, in_channels=[256, 512, 1024], attribute_dict=DTLD_ATTRIBUTES)
model2 = YOLOX(backbone2, head2)

print(get_model_info(model2, (640, 640)))
model2.eval()
res2 = model2(dummy_input)
print(res2)
print(res2.shape)

Params: 57.72M, Gflops: 175.29
tensor([[[ 3.9787e-01, -7.5917e-02,  7.9403e+00,  ...,  4.8492e-01,
           5.0616e-01,  5.0299e-01],
         [ 8.3979e+00, -7.5918e-02,  7.9403e+00,  ...,  4.8492e-01,
           5.0616e-01,  5.0299e-01],
         [ 1.6398e+01, -7.5918e-02,  7.9403e+00,  ...,  4.8492e-01,
           5.0616e-01,  5.0299e-01],
         ...,
         [ 5.4365e+02,  6.0641e+02,  3.2038e+01,  ...,  5.1194e-01,
           5.0040e-01,  4.8991e-01],
         [ 5.7565e+02,  6.0641e+02,  3.2038e+01,  ...,  5.1194e-01,
           5.0040e-01,  4.8991e-01],
         [ 6.0765e+02,  6.0641e+02,  3.2038e+01,  ...,  5.1194e-01,
           5.0040e-01,  4.8991e-01]]], grad_fn=<AsStridedBackward>)
torch.Size([1, 8400, 39])


In [9]:
res2[0][0]

tensor([ 0.3979, -0.0759,  7.9403,  8.0901,  0.5019,  0.5155,  0.5098,  0.4976,
         0.5076,  0.5047,  0.4951,  0.4945,  0.5094,  0.4878,  0.5005,  0.4880,
         0.4861,  0.5030,  0.5126,  0.4844,  0.5019,  0.5087,  0.4887,  0.5034,
         0.4991,  0.5075,  0.4970,  0.4882,  0.4887,  0.4858,  0.4876,  0.5065,
         0.5025,  0.4844,  0.4852,  0.5142,  0.4849,  0.5062,  0.5030],
       grad_fn=<SelectBackward>)

In [48]:
import torch.nn.functional as F

a = F.one_hot(torch.tensor((0,1,2,0)).to(torch.int64), 3).float().repeat(1, 2, 1)
print(a.shape)
a

torch.Size([1, 8, 3])


tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [1., 0., 0.],
         [1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.],
         [1., 0., 0.]]])

In [21]:
a.unsqueeze(1)

tensor([[[1.]],

        [[1.]],

        [[1.]]])

In [50]:
gt_attr=torch.tensor([[0., 1., 1., 1., 0., 0., 2., 1.],
        [0., 1., 0., 1., 0., 2., 2., 0.],
        [0., 1., 1., 1., 0., 0., 2., 1.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 0., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 0., 0., 1., 5.],
        [0., 0., 1., 1., 2., 5., 2., 7.],
        [0., 1., 1., 1., 2., 5., 2., 7.],
        [0., 1., 1., 1., 2., 5., 2., 7.],
        [0., 0., 1., 1., 0., 0., 1., 5.]])
gt_attr

tensor([[0., 1., 1., 1., 0., 0., 2., 1.],
        [0., 1., 0., 1., 0., 2., 2., 0.],
        [0., 1., 1., 1., 0., 0., 2., 1.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 0., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 1., 5., 4., 7.],
        [0., 1., 1., 1., 0., 0., 1., 5.],
        [0., 0., 1., 1., 2., 5., 2., 7.],
        [0., 1., 1., 1., 2., 5., 2., 7.],
        [0., 1., 1., 1., 2., 5., 2., 7.],
        [0., 0., 1., 1., 0., 0., 1., 5.]])

In [56]:
F.one_hot(gt_attr[:, 0].to(torch.int64), len(DTLD_ATTRIBUTES['orientation'])).shape

torch.Size([12, 2])

In [57]:
F.one_hot(gt_attr[:, 7].to(torch.int64), len(DTLD_ATTRIBUTES['pictogram'])).shape

torch.Size([12, 10])

In [84]:
attr_onehot = []
for attr_idx, attr_values in enumerate(DTLD_ATTRIBUTES.values()):
    attr_onehot.append(
        F.one_hot(gt_attr[:, attr_idx].to(torch.int64), len(attr_values)).float()
    )

In [85]:
attr_onehot = torch.cat(attr_onehot, 1)

In [86]:
attr_onehot

tensor([[1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 

In [87]:
attr_onehot.shape

torch.Size([12, 33])

In [88]:
attr_target = torch.zeros((20, 33))
attr_target

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [89]:
fg_mask = torch.tensor([False, True, True, True, False, True, False, True, False, True,
                        True, False, True, True, False, True, False, False, True, True])
fg_mask

tensor([False,  True,  True,  True, False,  True, False,  True, False,  True,
         True, False,  True,  True, False,  True, False, False,  True,  True])

In [90]:
attr_target[fg_mask] = attr_onehot

In [91]:
attr_onehot

tensor([[1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 

In [92]:
attr_onehot.shape

torch.Size([12, 33])

In [93]:
ttt=torch.tensor([0.0000, 1.2002, 1.2002, 1.2002, 2.4004, 6.0000, 2.4004, 8.3984])

In [94]:
ttt

tensor([0.0000, 1.2002, 1.2002, 1.2002, 2.4004, 6.0000, 2.4004, 8.3984])

In [99]:
F.one_hot(ttt.to(torch.int64), 10).float()

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])